-- ==============================================================================
-- 🐘 DataKern Data Engineering — Session 3
-- EXERCISE 5: SQL Grain Traps & Analytics Engineering
--
-- Goal: Master SQL logical execution order, avoid dangerous grain traps 
-- (double-counting), write diagnostic queries, and build your first Gold model.
-- ==============================================================================

-- -----------------------------------------------------------------------------
-- PUZZLE 1: The Double-Counting Grain Trap (Debugging)
--
-- A junior analyst was asked: "How many unique orders were placed in each state?"
-- They wrote the following query:
--
-- SELECT 
--     c.customer_state,
--     COUNT(*) AS total_orders
-- FROM silver.customers AS c
-- JOIN silver.orders AS o 
--     ON c.customer_id = o.customer_id
-- JOIN silver.order_items AS oi 
--     ON o.order_id = oi.order_id
-- GROUP BY c.customer_state
-- ORDER BY total_orders DESC;
--
-- 1. What is the bug? What is COUNT(*) actually counting here?
--    Answer: 
--
-- 2. Rewrite the query below so that it correctly counts the number of DISTINCT
--    orders per customer state:
-- -----------------------------------------------------------------------------

-- -> Write your corrected query below:




-- -----------------------------------------------------------------------------
-- PUZZLE 2: The Logical Execution Order Error
--
-- Another analyst tries to filter order items where the total cost 
-- (price + freight) exceeds 200:
--
-- SELECT 
--     order_id,
--     order_item_id,
--     (price + freight_value) AS total_item_cost
-- FROM silver.order_items
-- WHERE total_item_cost > 200.00;
--
-- PostgreSQL throws an error: 
--   ERROR: column "total_item_cost" does not exist!
--
-- 1. Explain WHY PostgreSQL throws this error by referencing the logical 
--    execution order (FROM -> WHERE -> GROUP BY -> SELECT -> ORDER BY -> LIMIT):
--    Answer: 
--
-- 2. Rewrite the query below so that it executes without error:
-- -----------------------------------------------------------------------------

-- -> Write your corrected query below:




-- -----------------------------------------------------------------------------
-- PUZZLE 3: Diagnostic Query (Unreviewed Orders)
--
-- In Session 3, we noticed that the relationship between `orders` and `reviews`
-- is not 1-to-1 guaranteed. 
--
-- Write a diagnostic query using a `LEFT JOIN` between `silver.orders` (as o)
-- and `silver.order_reviews` (as r) to find all orders that have NO review record.
-- Return the `order_id`, `order_status`, and `order_purchase_timestamp`.
-- Limit the output to 10 rows.
-- -----------------------------------------------------------------------------

-- -> Write your query below:




-- -----------------------------------------------------------------------------
-- PUZZLE 4: Building Your First Gold Business Model
--
-- The Finance and Merchandise teams need a report answering:
-- "What is the total revenue (price + freight) and total number of distinct 
--  orders generated by each product category?"
--
-- Requirements:
-- - Join `silver.order_items` (as oi) and `silver.products` (as p).
-- - Exclude products where `product_category_name` is NULL.
-- - Calculate `total_revenue` as SUM(oi.price + oi.freight_value) rounded to 2 decimals.
-- - Calculate `order_count` as COUNT(DISTINCT oi.order_id).
-- - Group by `p.product_category_name`.
-- - Order by `total_revenue` descending.
-- - Limit to the top 10 categories.
-- -----------------------------------------------------------------------------

-- -> Write your Gold aggregation query below:


